name: Create Project

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  DBMprojectName: "GithubCICD"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "su@dbmaestro.com"
  DBMauthToken: "xe1lwMC1tT5thurFSnjkoLNq2N32QPqY"
  DBMserver: "localhost:8017"
  packages_path: "./packages/"
  db_name: "db1"
  agent_jar_parent_path: "./agentjar/"
  agent_jar_path: "./agentjar/DBmaestroAgent.jar"

 
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "project name"
  #push:
  #  branches:
  #    - dev
jobs:
  # Job executed for Package Precheck. 
  # Triggered when a pull request is merged into Dev branch 
  import-project:
    runs-on: self-hosted
    steps:
      - name: Get DBMaestroAgent.jar file
        # Obtains the DBMaestroAgent.jar from the repository
        uses: dbmaestrodev/dbm-github-actions/get-dbmagent-jar@latest
        with: 
          version: "v23.4.2.11298"
          target_path: ${{ env.agent_jar_parent_path }} 

      - name: Echo
        run: |
          pwd
          ls -la

      - name: Update package.json version
        uses: restackio/update-json-file-action@2.1
        with:
          file: ./projectimport.json
          fields: "{\"ProjectName\":\"ImportProject\"}"

      - name: Create Project
        run: |
          java -jar "${{ env.agent_jar_path }}" -ImportProject -FilePath "./home/sergio/projectimport.json"  -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"
            

