name: Deployment Workflow

env:
  RUNNERS_OPTIONS: -c cookies=enabled
  DBMprojectName: "GithubCICD"
  DBMauthType: "DBmaestroAccount"
  DBMuserName: "su@dbmaestro.com"
  DBMauthToken: "zhsiecDKHTGeZBodgykvX1O5H0E5YzaI"
  DBMserver: "ser1:8017"
  packages_path: "./packages/"

  agent_jar_parent_path: "./agentjar/"
  agent_jar_path: "./agentjar/DBmaestroAgent.jar"

 
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package folder name where the scripts to be deployed are located"
  #push:
  #  branches:
  #    - dev
jobs:
  # Job executed for Package Precheck. 
  # Triggered when a pull request is merged into Dev branch 
  precheck:
    runs-on: self-hosted
    steps:
      - name: Checkout packages code
        uses: actions/checkout@v4
        with: 
          ref: dev
          
      - name: Get DBMaestroAgent.jar file
        # Obtains the DBMaestroAgent.jar from the repository
        uses: dbmaestrodev/dbm-github-actions/get-dbmagent-jar@latest
        with: 
          version: "v24.1.0.11442"
          target_path: ${{ env.agent_jar_parent_path }} 

#      - name: Log Branch Name 
#        run: | 
#            BRANCH_NAME=$(git log -1 --pretty=format:'%s' | sed 's/^Merge branch //;s/ into.*//' | sed 's/origin\///')
#            echo "Merged branch name: $BRANCH_NAME"

#      - name: Create Package
#        run: |
#            PACKAGE_PATH="${{ env.packages_path }}${{ github.event.inputs.package_name }}/" 
#            echo "Package Path $PACKAGE_PATH"
#            java -jar "${{ env.agent_jar_path }}" -CreateManifestFile -PathToScriptsFolder "$PACKAGE_PATH" 
#            ZIP_PATH="${{ env.packages_path }}${{ inputs.package_name }}.tar" 
#            tar -cvf "$ZIP_PATH" -C "${{ env.packages_path }}" ${{ github.event.inputs.package_name }}
#            echo 'java -jar "${{ env.agent_jar_path }}" -Package -ProjectName "${{ env.DBMprojectName }}" -IgnoreScriptWarnings True -FilePath "${{ env.packages_path }}${{ github.event.inputs.package_name }}.tar" -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"'
#            java -jar "${{ env.agent_jar_path }}" -Package -ProjectName "${{ env.DBMprojectName }}" -IgnoreScriptWarnings True -FilePath "$ZIP_PATH" -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}"

      - name: Create Package
        uses: dbmaestrodev/dbm-github-actions/dbm-create-package@latest
        with:
          package_name: ${{ inputs.package_name }}
          packages_path: ${{ env.packages_path }}
          project_id: ${{ env.DBMprojectName }}
          server: ${{ env.DBMserver }}
          user_name: ${{ env.DBMuserName }}
          password: ${{ env.DBMauthToken }}
          jar_path: ${{ env.agent_jar_path }}

      - name: Upgrade RS
        shell: bash
        run: |
            set +e
            output=$(java -jar "${{ env.agent_jar_path }}" -Upgrade -ProjectName ${{ env.DBMprojectName }} -EnvName "Release Source" -PackageName "github.event.inputs.package_name" -Server "${{ env.DBMserver }}" -UseSSL False -AuthType DBmaestroAccount -UserName "${{ env.DBMuserName }}" -Password "${{ env.DBMauthToken }}" 2>&1 )
            exit_code=$?
            echo "exit code:"
            echo "$exit_code"
            echo "complete output"
            echo "$output"
            filtered_output=$(echo "$output" | grep "Error executing")
            echo "filtered output:"
            echo "$filtered_output"


